require_recipe "apt"
require_recipe "build-essential"
require_recipe "openssl"
require_recipe "libssl-dev"
require_recipe "ruby"
require_recipe "subversion"
require_recipe "sudo"
require_recipe "nodejs"
